### ISSUE TITLE
Adding Meme Component in Application

### ISSUE THREAD

**Issue by zanemooney** [barrycumbie/animated-octo-adventure#156]
### Developer Story Card:
**As a** dev
**I want** a meme tab in my app
**So that** I can have happiness in my life

### Tasks:
- [x] Start by creating a new branch using: `git checkout -b iss156`
- [x] Make a new component using: `ng g c meme'
- [x] Add some cool code and funny pictures to give dopamine in life
- [ ] ???
- [ ] Profit

### Step-By-Step Guide to Testing:
- [ ] `git checkout -b iss156` on GitBash to pull down our code
- [ ] fire up server.js & ng serve 
- [ ] go to localhost:4200
- [ ] laugh at our dumb gif
- [ ] profit w/ us!
