### ISSUE TITLE
New Feature on Comp for Delta

### ISSUE THREAD

**Issue by maceyraejones** [barrycumbie/animated-octo-adventure#158]
###  User Story
**I am...** student user
**I want to...** look at the calendar 
**So I can...** see my schedule

### Tasks

- [ ] make new feature on our component
- [ ] different team
- [ ] our feature must be tested
- [ ] test other team's feature
- [ ] write a test (steps of what to do)

**Comment by esthergiles** [comment]
We tested the weather snippet team's component on 2/3/2022
