### ISSUE TITLE
Add button feature to tag component.

### ISSUE THREAD

**Issue by zachcutshall** [barrycumbie/animated-octo-adventure#165]
# User Story
**As a** user
**I want to** add tags
**So that** I can better filter my results

### Task
- [ ] Add a button to Tag Component
- [ ] Different team
- [ ] Make the button that says "Add Tag"
- [ ] Test another groups test
- [ ] Write a test case

### Testing

- [ ] ```git checkout -b iss165``` to pull down our code
- [ ]  start node.js and ng serve
- [ ]  to view the page go to localhost:4200
- [ ]  click the button to your heart's content
