### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by urielkodia** [barrycumbie/animated-octo-adventure#173]
### Task

- [ ] add a line of code into the dev-team
- [ ] and do a pull request 
- [ ] submit the link into your canvas
